### ISSUE TITLE
cannot find module tika

### ISSUE THREAD

**Issue by henrysachs** [ICIJ/node-tika#22]
just copied the code from your example and get the following error:

module.js:529
    throw err;
    ^

Error: Cannot find module 'tika'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/henrysachs/move-search/backend/node_approach/events.js:1:74)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by henrysachs** [comment]
installed the wrong npm package but this doesnt resolve my other issue with the package
